### ISSUE TITLE
Issues with BIOS modding on Razer blade 15 2020 version

### ISSUE THREAD

**Issue by ManjunathaN** [Mother-FKR/RazerBlade15-Base-Model-Hackintosh#6]
I'm trying to mod BIOS on Razer blade 15 2020 version and I'm getting this error -
`18 - Error: Secure Flash Rom Verify Fail`

How do I resolve this issue and has anyone tried this repo on 2020 model?

**Comment by tyson-hu** [comment]
Are you using AFU with the version`5.02.0031`, basically it is a security check error, BIOS you saved is not signed BIOS since it's a direct chip dump, so can't be used with AFU like you are trying. If the version is latest, try mod on other computer. I also ran into some issues on AFU, like software crashed while trying saving modded BIOS, which solved by doing this on another computer. Wish this could help you. 
Also, I'm sorry to tell you that I have not seen any repo on 2020 model, but since only cpu(IGPU still the same[UHD630]), graphic card(not really matter for Hackintosh), Network Card(for `AX201` try [itlwm](https://github.com/OpenIntelWireless/itlwm)), Screen and Audio not sure, other should be fine.

**Comment by ManjunathaN** [comment]
Thanks for the response.

> Are you using AFU with the version5.02.0031, basically it is a security check error, BIOS you saved is not signed BIOS since it's a direct chip dump, so can't be used with AFU like you are trying.

Yes Im using AFU v5.02.0031. For sanity test, I dumped the rom from the chip directly, and tried to flash it with the same rom. Thats when I got this error.

> I also ran into some issues on AFU, like software crashed while trying saving modded BIOS, which solved by doing this on another computer. Wish this could help you.

I do have mac, but if can send me the links to do this, it will very helpful.

> Also, I'm sorry to tell you that I have not seen any repo on 2020 model, but since only cpu(IGPU still the same[UHD630]), graphic card(not really matter for Hackintosh), Network Card(for AX201 try itlwm), Screen and Audio not sure, other should be fine.

Yes. I've not seen it anywhere. TBH, I wanted to give it a try because most of the configs were more or less same. I've a compatible network card, and doing it on separate sabrent ssd.

**Comment by tyson-hu** [comment]
Sorry to reply you at this time, I'm really busy at this week. But, if that still does not work, I can not give your more useful information, because as you know, our BIOS not the same one, Razer might change something which could effect this error appear. But that doesn't mean you can not use Hackintosh, we mod BIOS for some hidden option, however we can use quirks in OpenCore to help us boot Hackintosh. Such as `AppleCpuPmCfgLock` and `AppleXcpmCfgLock`, these could help the machine who can't unlock cfg. `DisableIOMapper` for the machine who can't disabled VT-D in BIOS. You could check the detail in [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/), Wish you join the Hackintosh and the process of making EFI :)
